apiVersion: aws.platformref.upbound.io/v1alpha1
kind: IRSA
metadata:
    name: xplane-external-secrets
    namespace: security
spec:
    deletionPolicy: Delete
    parameters:
        condition: StringEquals
        # Reference: https://github.com/external-secrets/external-secrets/blob/main/terraform/aws/modules/cluster/irsa.tf
        policyDocument: |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ssm:GetParameter*",
                            "ssm:PutParameter",
                            "ssm:DescribeParameters",
                            "ssm:DeleteParameter*",
                            "ssm:AddTagsToResource",
                            "ssm:ListTagsForResource",
                            "ssm:RemoveTagsFromResource",
                            "tag:GetResources"
                        ],
                        "Resource": [
                            "*"
                        ]
                    }
                ]
            }

        serviceAccount:
            name: external-secrets
            namespace: kube-system
