apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/kyverno
  - ../base/cert-manager
  - ../base/rbac
  - external-secrets
  - echo-gw-clusterpolicy.yaml
  - echo-unsecure-gw-clusterpolicy.yaml
  - platform-gw-clusterpolicy.yaml
