apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      version: "1.14.0"
  interval: 10m0s
  upgrade:
    force: true
  install:
    remediation:
      retries: 3
  values:
    bandwidthManager:
      enabled: true
    bpf:
      preallocateMaps: true
    egressMasqueradeInterfaces: eth0
    eni:
      enabled: true
    installNoConntrackIptablesRules: true
    ipam:
      mode: eni
    kubeProxyReplacement: strict
    operator:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      rollOutPods: true # Reload pods when the configmap is updated
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
    routingMode: native
    tunnel: disabled
    envoy:
      enabled: true
      resources:
        limits:
          memory: 300Mi
        requests:
          cpu: 200m
          memory:
    gatewayAPI:
      enabled: true
