---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-controller
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/mycluster-0/crossplane/controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: eks-mycluster-0-vars
        optional: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: crossplane
      namespace: crossplane-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-providers
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./infrastructure/mycluster-0/crossplane/providers
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: eks-mycluster-0-vars
        optional: true
  dependsOn:
    - name: crossplane-controller
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  path: ./infrastructure/mycluster-0
  postBuild:
    substitute:
      domain_name: "cloud.ogenki.io"
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: eks-mycluster-0-vars
        optional: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-controller
    - name: crossplane-providers
