apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  prune: true
  interval: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./security/mycluster-0
  postBuild:
    substitute:
      domain_name: "cloud.ogenki.io"
    substituteFrom:
      - kind: ConfigMap
        name: eks-mycluster-0-vars
      - kind: Secret
        name: eks-mycluster-0-vars
        optional: true
  dependsOn:
    - name: crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: external-secrets
      namespace: security
