apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: platform-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      hostname: "*.cloud.ogenki.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
                - observability
                - flux-system
      tls:
        mode: Terminate
        certificateRefs:
          - name: platform-tls
