apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: tls-shared-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      hostname: "*.cloud.ogenki.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: echo-tls
