apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

# reference: https://github.com/upbound/platform-ref-aws/tree/main/package/cluster/irsa
resources:
  - environmentconfig.yaml
  - irsa-composition.yaml
  - irsa-definition.yaml
  - providerconfig.yaml
