---
# This cluster resource needs to be moved somewhere else
# After the eso deployment
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: security
      region: ${region}
      service: SecretsManager
  refreshInterval: 0
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: temporal
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: observability/kube-prometheus-stack/grafana-admin
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kube-prometheus-stack-grafana-admin
