apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: weave-gitops
spec:
  parentRefs:
    - name: platform-gateway
      namespace: infrastructure
  hostnames:
    - "grafana-${cluster_name}.${domain_name}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
